using System;
using System.Collections.Generic;
using ReadTrack.Recommendations.Domain.Enums;

namespace ReadTrack.Recommendations.Application.DTOs
{
    /// <summary>
    /// Data Transfer Object representing the current status and potential result of a recommendation job.
    /// Used by the API to respond to polling requests.
    /// </summary>
    public record RecommendationJobStatusDto
    {
        /// <summary>
        /// The unique identifier of the job.
        /// </summary>
        public Guid JobId { get; init; }

        /// <summary>
        /// The current status of the job.
        /// </summary>
        public RecommendationJobStatus Status { get; init; }

        /// <summary>
        /// The string representation of the status for client consumption.
        /// </summary>
        public string StatusDescription => Status.ToString();

        /// <summary>
        /// The failure reason, if the job status is Failed. Null otherwise.
        /// </summary>
        public string? FailureReason { get; init; }

        /// <summary>
        /// The generated recommendations. This will be null unless the Status is Completed.
        /// </summary>
        public List<RecommendationResultDto>? Results { get; init; }

        /// <summary>
        /// The timestamp when the job was last updated.
        /// </summary>
        public DateTime UpdatedAt { get; init; }
    }

    /// <summary>
    /// Represents a single book recommendation within the job result.
    /// </summary>
    public record RecommendationResultDto
    {
        /// <summary>
        /// The unique ID of the recommendation result.
        /// </summary>
        public Guid RecommendationId { get; init; }

        /// <summary>
        /// The title of the recommended book.
        /// </summary>
        public string Title { get; init; } = string.Empty;

        /// <summary>
        /// The author(s) of the recommended book.
        /// </summary>
        public string Author { get; init; } = string.Empty;

        /// <summary>
        /// The explanation generated by the AI for why this book was recommended.
        /// </summary>
        public string Reason { get; init; } = string.Empty;

        /// <summary>
        /// The ISBN (10 or 13) if available/identified.
        /// </summary>
        public string? Isbn { get; init; }

        /// <summary>
        /// Confidence score (0.0 - 1.0) of the recommendation relevance.
        /// </summary>
        public double ConfidenceScore { get; init; }
    }
}